# Generated by Django 3.0.7 on 2020-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200620_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('link', models.TextField()),
                ('author', models.CharField(max_length=200)),
            ],
        ),
    ]
